name: Deploy RealEstate App Backend

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: |
           ${{ secrets.SSH_P_K }}
           ${{ secrets.SSH_P_K_2 }}
          script: |
            cd ~/realestate_app/realestate-projects-tracker
            
            git pull origin main
            
            docker compose up -d --build backend
            
            docker image prune -f